"""
Analogy Verifier for PCM Translation Pipeline.

Validates that analogies generated by MotivationAgent are mathematically
sound and do not introduce known misconceptions.

Verification flow:
  1. Check against built-in misconception dictionary (O(n), fast)
  2. LLM critic evaluation with math professor persona (0-100 score)
  3. Decision: PASS (>=70) / WARN (50-69, add scope limiter) / FAIL (<50, reject)

If FAIL, caller can supply a regenerate_fn; the verifier retries up to
MAX_RETRIES times before accepting the last result with a warning.
"""

from __future__ import annotations

import re
import requests
from dataclasses import dataclass, field
from typing import Callable, List, Optional


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class VerificationResult:
    """Result of a single analogy verification."""

    passed: bool            # True for PASS or WARN
    score: int              # 0-100
    level: str              # "PASS" | "WARN" | "FAIL"
    reason: str             # Human-readable explanation
    analogy: str            # Possibly modified analogy (scope limiter added for WARN)
    flagged_misconception: Optional[str] = None  # Name of matched misconception if any


@dataclass
class MisconceptionEntry:
    """A known bad analogy pattern with explanation."""

    concept: str
    bad_pattern: str        # regex or keyword pattern
    why_wrong: str
    good_alternative: str = ""


# ---------------------------------------------------------------------------
# Built-in misconception dictionary
# ---------------------------------------------------------------------------

MISCONCEPTIONS: List[MisconceptionEntry] = [
    MisconceptionEntry(
        concept="infinity",
        bad_pattern=r"무한(?:은|이|을|의)?\s*(?:매우\s*큰|아주\s*큰|엄청\s*큰)\s*수",
        why_wrong="무한은 수가 아니라 크기의 개념. ∞+1=∞는 자연수에서 성립하지 않음.",
        good_alternative="무한은 어떤 유한한 수보다도 크다는 성질을 가진 개념",
    ),
    MisconceptionEntry(
        concept="limit",
        bad_pattern=r"극한.{0,30}(?:도달|닿|이르)|(?:도달|이르).{0,10}극한",
        why_wrong="극한은 도달하는 값이 아니라 접근하는 값. 실제로 도달하지 않을 수도 있음.",
        good_alternative="극한은 무한히 가까이 갈 때 향하는 목적지",
    ),
    MisconceptionEntry(
        concept="continuity",
        bad_pattern=r"그래프가\s*끊기지\s*않|연속(?:은|이|을|함수)?.{0,20}(?:끊기지\s*않|이어진\s*함수|붙어)",
        why_wrong="연속성은 시각적 연결이 아니라 ε-δ 조건으로 정의됨. Weierstrass 함수는 시각적으로 불연속처럼 보여도 연속.",
        good_alternative="연속은 입력의 작은 변화가 출력의 작은 변화만을 일으키는 성질",
    ),
    MisconceptionEntry(
        concept="homeomorphism",
        bad_pattern=r"(?:커피잔|도넛|토러스).*같다(?:고|는)?",
        why_wrong="위상동형은 특정 구체적 경우에만 성립하는 비유. 일반화하면 오해 유발.",
        good_alternative="위상동형은 연속 변형(늘리기/구부리기)으로 서로 변환 가능한 공간",
    ),
    MisconceptionEntry(
        concept="vector_space",
        bad_pattern=r"벡터(?:는|란|이란)?\s*화살표",
        why_wrong="벡터가 화살표라는 비유는 기하학적 벡터에만 해당. 함수공간, 다항식공간 등에서 적용 불가.",
        good_alternative="벡터는 덧셈과 스칼라 곱셈 연산을 만족하는 원소의 일반적 개념",
    ),
    MisconceptionEntry(
        concept="derivative",
        bad_pattern=r"미분(?:은|이란)?\s*(?:순간\s*변화율|기울기)(?:이다|다)$",
        why_wrong="순간변화율은 직관적 설명이지만, 도함수의 극한 정의 없이 단정하면 오개념 유발.",
        good_alternative="미분은 함수의 극한적 변화율로, 접선의 기울기로 시각화 가능",
    ),
    MisconceptionEntry(
        concept="infinity_types",
        bad_pattern=r"모든\s*무한(?:은|이|의)\s*같다",
        why_wrong="Cantor의 대각선 논법에 의해 무한에도 크기가 있음(가산/비가산 구분).",
        good_alternative="자연수의 무한과 실수의 무한은 크기가 다름",
    ),
    MisconceptionEntry(
        concept="probability",
        bad_pattern=r"확률\s*0(?:은|이란)?\s*불가능",
        why_wrong="연속 확률분포에서 특정 점의 확률은 0이지만 불가능한 사건이 아님.",
        good_alternative="확률 0은 사건이 발생하지 않는다는 의미가 아니라 측도 0임을 의미",
    ),
    MisconceptionEntry(
        concept="matrix_multiplication",
        bad_pattern=r"행렬\s*곱셈(?:은|이)?\s*(?:순서가\s*무관|교환)",
        why_wrong="행렬 곱셈은 일반적으로 비가환(AB ≠ BA).",
        good_alternative="행렬 곱셈은 순서가 중요하며, AB와 BA는 일반적으로 다름",
    ),
    MisconceptionEntry(
        concept="open_set",
        bad_pattern=r"열린\s*집합(?:은|이란)?\s*(?:경계가\s*없|끝이\s*없)",
        why_wrong="열린 집합은 경계점을 포함하지 않는 집합이며, 유계일 수 있음. (0,1)은 열린 집합.",
        good_alternative="열린 집합은 모든 점 주변에 완전히 포함되는 작은 공이 존재하는 집합",
    ),
]


# ---------------------------------------------------------------------------
# Analogy Verifier
# ---------------------------------------------------------------------------

class AnalogyVerifier:
    """
    Validates analogies for mathematical soundness.

    Scoring thresholds:
      - score >= 70 : PASS  (accept as-is)
      - 50 <= score < 70 : WARN  (add scope-limiting prefix, then accept)
      - score < 50 : FAIL  (reject; caller can trigger regeneration)
    """

    MAX_RETRIES = 2
    PASS_THRESHOLD = 70
    WARN_THRESHOLD = 50

    SCOPE_LIMITER_PREFIX = (
        "직관적 이해를 위한 비유로, "
        "수학적으로 엄밀하지 않을 수 있습니다: "
    )

    def __init__(
        self,
        model: str = "qwen2.5:7b",
        ollama_url: str = "http://localhost:11434/api/generate",
        misconceptions: Optional[List[MisconceptionEntry]] = None,
    ):
        self.model = model
        self.ollama_url = ollama_url
        self.misconceptions = misconceptions if misconceptions is not None else MISCONCEPTIONS

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def verify(
        self,
        analogy_text: str,
        formal_definition: str,
        domain: str = "mathematics",
    ) -> VerificationResult:
        """
        Verify a single analogy.

        Parameters
        ----------
        analogy_text:
            The analogy/motivation text to verify (Korean).
        formal_definition:
            The corresponding formal mathematical definition (used as context).
        domain:
            Mathematical domain (e.g. "algebra", "topology").

        Returns
        -------
        VerificationResult
        """
        # Step 1: misconception dictionary check (fast, no LLM)
        misconception_hit, misconception_name, why_wrong = self._check_misconceptions(analogy_text)
        if misconception_hit:
            return VerificationResult(
                passed=False,
                score=0,
                level="FAIL",
                reason=f"알려진 오개념 패턴 감지: {misconception_name}. {why_wrong}",
                analogy=analogy_text,
                flagged_misconception=misconception_name,
            )

        # Step 2: LLM critic evaluation
        score, reason = self._evaluate_with_llm(analogy_text, formal_definition, domain)

        level, modified_analogy = self._decide(score, analogy_text)
        return VerificationResult(
            passed=(level != "FAIL"),
            score=score,
            level=level,
            reason=reason,
            analogy=modified_analogy,
        )

    def verify_and_fix(
        self,
        analogy_text: str,
        formal_definition: str,
        domain: str = "mathematics",
        regenerate_fn: Optional[Callable[[], str]] = None,
    ) -> VerificationResult:
        """
        Verify and optionally regenerate on FAIL (up to MAX_RETRIES times).

        Parameters
        ----------
        analogy_text:
            Initial analogy to verify.
        formal_definition:
            Formal definition for context.
        domain:
            Mathematical domain.
        regenerate_fn:
            Callable that returns a new analogy string.
            If None, does not retry on FAIL.

        Returns
        -------
        VerificationResult of the best accepted result, or last FAIL if all retries exhausted.
        """
        result = self.verify(analogy_text, formal_definition, domain)

        if result.passed or regenerate_fn is None:
            return result

        for attempt in range(self.MAX_RETRIES):
            new_analogy = regenerate_fn()
            if not new_analogy:
                break
            result = self.verify(new_analogy, formal_definition, domain)
            if result.passed:
                return result

        # All retries exhausted; return last result (FAIL) with warning note
        result.reason = f"[최대 재시도 도달] {result.reason}"
        return result

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _check_misconceptions(self, analogy_text: str):
        """
        Check analogy against built-in misconception dictionary.

        Returns (hit: bool, concept_name: str, why_wrong: str)
        """
        for entry in self.misconceptions:
            if re.search(entry.bad_pattern, analogy_text, re.IGNORECASE):
                return True, entry.concept, entry.why_wrong
        return False, "", ""

    def _evaluate_with_llm(
        self,
        analogy_text: str,
        formal_definition: str,
        domain: str,
    ):
        """
        Ask LLM (math professor persona) to score the analogy 0-100.

        Returns (score: int, reason: str). Falls back to (75, "LLM 불가") on failure.
        """
        prompt = (
            f"당신은 엄격한 수학 교수입니다. 다음 수학적 비유를 평가하세요.\n\n"
            f"[공식 정의 ({domain})]:\n{formal_definition[:400]}\n\n"
            f"[비유/직관 설명]:\n{analogy_text}\n\n"
            f"다음 기준으로 0-100점 사이의 점수를 매기세요:\n"
            f"- 수학적 정확성 (40점): 비유가 공식 정의와 모순되지 않는가?\n"
            f"- 범위 명확성 (25점): 비유의 적용 한계가 명시되어 있는가?\n"
            f"- 오개념 위험 (20점): 알려진 수학적 오개념을 유발하지 않는가?\n"
            f"- 도메인 적합성 (15점): 해당 분야 독자에게 적합한가?\n\n"
            f"반드시 다음 형식으로만 답하세요:\n"
            f"SCORE: <숫자>\nREASON: <한 문장 이유>"
        )

        try:
            resp = requests.post(
                self.ollama_url,
                json={
                    "model": self.model,
                    "prompt": prompt,
                    "stream": False,
                    "options": {"temperature": 0.1, "num_predict": 100},
                },
                timeout=45,
            )
            resp.raise_for_status()
            text = resp.json().get("response", "")
            score = self._parse_score(text)
            reason = self._parse_reason(text)
            return score, reason
        except Exception:
            # Graceful fallback: assume acceptable (score 75)
            return 75, "LLM 평가 불가 - 기본값 75 적용"

    def _parse_score(self, llm_response: str) -> int:
        """Extract integer score from LLM response. Defaults to 75 on parse failure."""
        match = re.search(r"SCORE\s*:\s*(\d+)", llm_response, re.IGNORECASE)
        if match:
            return min(100, max(0, int(match.group(1))))
        # Fallback: look for any number 0-100 in the text
        numbers = re.findall(r"\b([0-9]{1,3})\b", llm_response)
        for n in numbers:
            v = int(n)
            if 0 <= v <= 100:
                return v
        return 75

    def _parse_reason(self, llm_response: str) -> str:
        """Extract reason from LLM response."""
        match = re.search(r"REASON\s*:\s*(.+)", llm_response, re.IGNORECASE)
        if match:
            return match.group(1).strip()
        return llm_response.strip()[:200]

    def _decide(self, score: int, analogy_text: str):
        """
        Map score to decision level and possibly modify analogy.

        Returns (level: str, modified_analogy: str)
        """
        if score >= self.PASS_THRESHOLD:
            return "PASS", analogy_text
        if score >= self.WARN_THRESHOLD:
            modified = self.SCOPE_LIMITER_PREFIX + analogy_text
            return "WARN", modified
        return "FAIL", analogy_text
