"""
Paper Synthesizer for PCM Translation Pipeline.

Generates a mini survey paper (심층 해설 논문) from a translated math section
by orchestrating 4 sub-agents in sequence:

  1. HistoryAgent   — historical context (Wikipedia API + LLM)
  2. IntuitionAgent — step-by-step intuitive explanation
  3. VisualizationAgent — domain-aware TikZ / Graphviz code
  4. ConceptMapAgent — prerequisite / application / generalisation map

Output: a Typst (.typ) source string ready to compile to PDF.

Usage:
    from src.pcm.core.paper_synthesizer import PaperSynthesizer

    synth = PaperSynthesizer()
    result = synth.synthesize(section)      # SynthesisResult
    print(result.typst_source)
    synth.save(result, "output/group_theory.typ")
"""

from __future__ import annotations

import json
import re
import requests
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class ConceptMap:
    """Concept connections generated by ConceptMapAgent."""
    prerequisites: list[str] = field(default_factory=list)
    applications: list[str] = field(default_factory=list)
    generalizations: list[str] = field(default_factory=list)
    special_cases: list[str] = field(default_factory=list)


@dataclass
class SynthesisResult:
    """Full output of PaperSynthesizer for a single section."""
    section_id: str
    title: str
    abstract: str
    history: str
    intuition: str
    visualization_code: str       # TikZ or Graphviz source
    visualization_strategy: str   # e.g. "tikzcd", "graphviz"
    concept_map: ConceptMap
    typst_source: str


# ---------------------------------------------------------------------------
# Helper: LLM call
# ---------------------------------------------------------------------------

_DEFAULT_OLLAMA_URL = "http://localhost:11434/api/generate"
_DEFAULT_MODEL = "qwen2.5:7b"


def _llm(
    prompt: str,
    model: str = _DEFAULT_MODEL,
    url: str = _DEFAULT_OLLAMA_URL,
    num_predict: int = 300,
    temperature: float = 0.3,
) -> str:
    """Call Ollama, return text. Returns empty string on failure."""
    try:
        resp = requests.post(
            url,
            json={
                "model": model,
                "prompt": prompt,
                "stream": False,
                "options": {"temperature": temperature, "num_predict": num_predict},
            },
            timeout=60,
        )
        resp.raise_for_status()
        return resp.json().get("response", "").strip()
    except Exception:
        return ""


# ---------------------------------------------------------------------------
# Sub-agents
# ---------------------------------------------------------------------------

class HistoryAgent:
    """
    Generates the historical background section.

    Optionally fetches a Wikipedia summary for each key term (no auth needed).
    Falls back gracefully when Wikipedia is unavailable.
    """

    WIKI_API = "https://en.wikipedia.org/api/rest_v1/page/summary/{term}"

    def __init__(
        self,
        model: str = _DEFAULT_MODEL,
        ollama_url: str = _DEFAULT_OLLAMA_URL,
        use_wikipedia: bool = True,
        wiki_timeout: int = 5,
    ):
        self.model = model
        self.ollama_url = ollama_url
        self.use_wikipedia = use_wikipedia
        self.wiki_timeout = wiki_timeout

    def _fetch_wiki(self, term: str) -> str:
        """Return 1-2 sentence Wikipedia summary, or empty string."""
        if not self.use_wikipedia:
            return ""
        try:
            url = self.WIKI_API.format(term=term.replace(" ", "_"))
            r = requests.get(url, timeout=self.wiki_timeout)
            if r.status_code == 200:
                return r.json().get("extract", "")[:400]
        except Exception:
            pass
        return ""

    def _extract_key_term(self, text: str) -> str:
        """Heuristically pull the first math term (capitalised or in parens)."""
        m = re.search(r"\(([A-Z][a-zA-Z ]{2,30})\)", text)
        if m:
            return m.group(1)
        m = re.search(r"\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)\b", text)
        if m:
            return m.group(1)
        return text.split(".")[0][:40]

    def generate(self, section: dict) -> str:
        """Return a 300-500 char historical background paragraph (Korean)."""
        title = section.get("title", section.get("section_id", "개념"))
        text = section.get("final_ko") or section.get("text", "")

        key_term = self._extract_key_term(text)
        wiki_ctx = self._fetch_wiki(key_term)

        prompt = (
            f"다음 수학 개념의 역사적 발전 과정을 학술 논문 도입부 스타일로 서술하세요.\n"
            f"- 개념이 등장한 시대적 배경과 동기\n"
            f"- 핵심 기여자와 그들이 해결하려 한 문제\n"
            f"- 현대적 정의로 발전하는 과정\n"
            f"- 한국어 300-500자로 작성\n\n"
            f"개념: {title}\n"
            f"원문 요약: {text[:300]}\n"
            + (f"Wikipedia 참고:\n{wiki_ctx}\n" if wiki_ctx else "")
            + "\n역사적 배경:"
        )
        result = _llm(prompt, model=self.model, url=self.ollama_url, num_predict=250)
        if not result:
            return f"{title}은(는) 수학의 핵심 개념 중 하나로, 오랜 역사를 통해 발전해왔습니다."
        return result


class IntuitionAgent:
    """
    Generates a step-by-step intuitive explanation without formulas.
    """

    def __init__(
        self,
        model: str = _DEFAULT_MODEL,
        ollama_url: str = _DEFAULT_OLLAMA_URL,
    ):
        self.model = model
        self.ollama_url = ollama_url

    def generate(self, section: dict) -> str:
        """Return a 3-5 step intuitive walkthrough (Korean)."""
        title = section.get("title", section.get("section_id", "개념"))
        text = section.get("final_ko") or section.get("text", "")
        domain = section.get("domain", "mathematics")

        prompt = (
            f"다음 {domain} 개념을 수식 없이 단계별로 직관적으로 설명하세요.\n"
            f"- 일상적인 비유나 구체적 예시를 사용하세요\n"
            f"- 3-4단계로 나눠서 '첫째:', '둘째:', ... 형식으로\n"
            f"- 수식 기호 대신 말로 표현하세요\n"
            f"- 한국어로 작성\n\n"
            f"개념: {title}\n"
            f"설명할 내용: {text[:400]}\n\n"
            f"단계별 직관 설명:"
        )
        result = _llm(prompt, model=self.model, url=self.ollama_url, num_predict=300)
        if not result:
            return f"이 개념은 수학의 핵심 구조를 나타냅니다. 구체적인 예시를 통해 이해할 수 있습니다."
        return result


class VisualizationAgent:
    """
    Generates domain-appropriate TikZ or Graphviz diagram code.

    Strategy map:
        category_theory → tikzcd (commutative diagrams)
        topology        → tikz_venn (containment diagrams)
        algebra         → graphviz (Hasse diagrams)
        analysis        → pgfplots (function graphs)
        linear_algebra  → tikz_arrow (vector/transformation diagrams)
        <default>       → tikz_generic
    """

    STRATEGY_MAP = {
        "category_theory": "tikzcd",
        "topology":        "tikz_venn",
        "algebra":         "graphviz",
        "analysis":        "pgfplots",
        "linear_algebra":  "tikz_arrow",
    }

    FALLBACK_TEMPLATES = {
        "graphviz": (
            'digraph concept {{\n'
            '  rankdir=BT\n'
            '  node [shape=ellipse]\n'
            '  "{title}" [shape=box, style=filled, fillcolor=lightblue]\n'
            '  "선행 개념" -> "{title}"\n'
            '  "{title}" -> "응용 분야"\n'
            '}}'
        ),
        "tikzcd": (
            '\\begin{{tikzcd}}\n'
            '  A \\arrow[r, "f"] & B \\arrow[d, "g"] \\\\\\\\\n'
            '  C \\arrow[u, "h"] & D\n'
            '\\end{{tikzcd}}'
        ),
        "default": (
            '\\begin{{tikzpicture}}\n'
            '  \\node[draw, rounded corners] (n) at (0,0) {{{title}}};\n'
            '  \\node[draw] (a) at (-2, -1.5) {{선행 개념}};\n'
            '  \\node[draw] (b) at (2, -1.5) {{응용 분야}};\n'
            '  \\draw[->] (a) -- (n);\n'
            '  \\draw[->] (n) -- (b);\n'
            '\\end{{tikzpicture}}'
        ),
    }

    def __init__(
        self,
        model: str = _DEFAULT_MODEL,
        ollama_url: str = _DEFAULT_OLLAMA_URL,
    ):
        self.model = model
        self.ollama_url = ollama_url

    def _get_strategy(self, domain: str) -> str:
        return self.STRATEGY_MAP.get(domain, "default")

    def generate(self, section: dict) -> tuple[str, str]:
        """
        Returns (code: str, strategy: str).

        code     — TikZ / Graphviz source
        strategy — strategy name used
        """
        title = section.get("title", section.get("section_id", "개념"))
        domain = section.get("domain", "mathematics")
        text = section.get("final_ko") or section.get("text", "")
        strategy = self._get_strategy(domain)

        prompt = (
            f"다음 수학 개념을 '{strategy}' 형식의 다이어그램 코드로 표현하세요.\n"
            f"- 코드 블록만 출력하고 설명 텍스트는 포함하지 마세요\n"
            f"- 노드 레이블에는 한국어를 사용하세요\n"
            f"- 컴파일 가능한 완전한 코드를 출력하세요\n\n"
            f"개념: {title} (도메인: {domain})\n"
            f"핵심 내용: {text[:250]}\n\n"
            f"{strategy} 코드:"
        )
        code = _llm(
            prompt, model=self.model, url=self.ollama_url,
            num_predict=200, temperature=0.2
        )

        if not code or len(code.strip()) < 20:
            tmpl_key = "graphviz" if strategy == "graphviz" else (
                "tikzcd" if strategy == "tikzcd" else "default"
            )
            code = self.FALLBACK_TEMPLATES[tmpl_key].format(title=title)

        return code, strategy


class ConceptMapAgent:
    """
    Generates a JSON concept map with 4 relation types.
    """

    def __init__(
        self,
        model: str = _DEFAULT_MODEL,
        ollama_url: str = _DEFAULT_OLLAMA_URL,
    ):
        self.model = model
        self.ollama_url = ollama_url

    def _fallback(self, title: str) -> ConceptMap:
        return ConceptMap(
            prerequisites=[f"{title} 기초 개념", "집합론"],
            applications=[f"{title} 응용 분야", "현대 수학"],
            generalizations=[f"일반화된 {title}"],
            special_cases=[f"{title}의 특수 사례"],
        )

    def generate(self, section: dict) -> ConceptMap:
        """Return a ConceptMap. Falls back to template on LLM/parse failure."""
        title = section.get("title", section.get("section_id", "개념"))
        text = section.get("final_ko") or section.get("text", "")

        prompt = (
            f"'{title}' 개념과 연결된 수학 분야를 분석하고 반드시 JSON 형식으로만 출력하세요.\n"
            f"다른 텍스트는 절대 포함하지 마세요.\n\n"
            f"원문: {text[:300]}\n\n"
            f"JSON 형식:\n"
            f'{{\n'
            f'  "prerequisites": ["선행 개념1", "선행 개념2"],\n'
            f'  "applications": ["응용 분야1", "응용 분야2"],\n'
            f'  "generalizations": ["일반화 버전1"],\n'
            f'  "special_cases": ["특수 케이스1", "특수 케이스2"]\n'
            f'}}'
        )

        raw = _llm(
            prompt, model=self.model, url=self.ollama_url,
            num_predict=200, temperature=0.1
        )

        # Extract JSON block
        json_match = re.search(r'\{[^{}]*"prerequisites"[^{}]*\}', raw, re.DOTALL)
        if json_match:
            try:
                data = json.loads(json_match.group())
                return ConceptMap(
                    prerequisites=data.get("prerequisites", [])[:4],
                    applications=data.get("applications", [])[:4],
                    generalizations=data.get("generalizations", [])[:4],
                    special_cases=data.get("special_cases", [])[:4],
                )
            except json.JSONDecodeError:
                pass

        return self._fallback(title)


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

class PaperSynthesizer:
    """
    Orchestrates 4 sub-agents to produce a mini survey paper in Typst format.

    Parameters
    ----------
    model:
        Ollama model name.
    use_wikipedia:
        Whether HistoryAgent should query Wikipedia API.
    """

    def __init__(
        self,
        model: str = _DEFAULT_MODEL,
        ollama_url: str = _DEFAULT_OLLAMA_URL,
        use_wikipedia: bool = True,
    ):
        self.model = model
        self.ollama_url = ollama_url
        self.history_agent = HistoryAgent(
            model=model, ollama_url=ollama_url, use_wikipedia=use_wikipedia
        )
        self.intuition_agent = IntuitionAgent(model=model, ollama_url=ollama_url)
        self.viz_agent = VisualizationAgent(model=model, ollama_url=ollama_url)
        self.map_agent = ConceptMapAgent(model=model, ollama_url=ollama_url)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def synthesize(self, section: dict) -> SynthesisResult:
        """
        Generate a mini survey paper for a single translated section.

        Parameters
        ----------
        section:
            Must have at least 'section_id' and one of 'final_ko' / 'text'.
            Optional: 'title', 'domain', 'block_type'.
        """
        sec_id = section.get("section_id", "unknown")
        title = section.get("title") or self._infer_title(section)
        section = {**section, "title": title}   # ensure title is set

        abstract = self._generate_abstract(section)
        history = self.history_agent.generate(section)
        intuition = self.intuition_agent.generate(section)
        viz_code, viz_strategy = self.viz_agent.generate(section)
        concept_map = self.map_agent.generate(section)

        typst_src = self._render_typst(
            section_id=sec_id,
            title=title,
            abstract=abstract,
            history=history,
            intuition=intuition,
            viz_code=viz_code,
            viz_strategy=viz_strategy,
            concept_map=concept_map,
        )

        return SynthesisResult(
            section_id=sec_id,
            title=title,
            abstract=abstract,
            history=history,
            intuition=intuition,
            visualization_code=viz_code,
            visualization_strategy=viz_strategy,
            concept_map=concept_map,
            typst_source=typst_src,
        )

    def save(self, result: SynthesisResult, path: str) -> Path:
        """Save Typst source to file. Returns the Path."""
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(result.typst_source, encoding="utf-8")
        return p

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _infer_title(self, section: dict) -> str:
        text = section.get("final_ko") or section.get("text", "")
        m = re.search(
            r"(?:정의|Theorem|Definition|Lemma|Proposition)\s*[\d.]*\s*\(([^)]+)\)",
            text, re.IGNORECASE,
        )
        if m:
            return m.group(1)
        return section.get("section_id", "수학 개념")

    def _generate_abstract(self, section: dict) -> str:
        title = section["title"]
        text = section.get("final_ko") or section.get("text", "")
        prompt = (
            f"다음 수학 개념을 학술 논문 초록(Abstract) 형식으로 1-2문단 요약하세요.\n"
            f"- 개념의 정의와 중요성을 간결하게\n"
            f"- 한국어 200자 내외\n\n"
            f"개념: {title}\n원문: {text[:400]}\n\n초록:"
        )
        result = _llm(
            prompt, model=self.model, url=self.ollama_url, num_predict=150
        )
        if not result:
            return f"{title}은(는) 현대 수학의 핵심 개념으로, 다양한 분야에 걸쳐 중요한 역할을 한다."
        return result

    def _render_typst(
        self,
        section_id: str,
        title: str,
        abstract: str,
        history: str,
        intuition: str,
        viz_code: str,
        viz_strategy: str,
        concept_map: ConceptMap,
    ) -> str:
        """Render Typst source string."""
        prereqs = "\n".join(f"  - {p}" for p in concept_map.prerequisites)
        apps = "\n".join(f"  - {a}" for a in concept_map.applications)
        gens = "\n".join(f"  - {g}" for g in concept_map.generalizations)
        cases = "\n".join(f"  - {c}" for c in concept_map.special_cases)

        return f"""\
// Auto-generated mini survey — section {section_id}
// Math Translation Study · PaperSynthesizer

#set text(font: "Noto Serif CJK KR", size: 10pt, lang: "ko")
#set heading(numbering: "1.")
#set page(margin: (x: 2.5cm, y: 2.5cm))

#align(center)[
  #text(16pt, weight: "bold")[{title}]
  #linebreak()
  #text(9pt, style: "italic")[수학 번역 연구 · 자동 생성 해설 논문 · 섹션 {section_id}]
]

#v(0.5em)
#line(length: 100%)
#v(0.3em)

*초록.* {abstract}

#line(length: 100%)

= 역사적 배경

{history}

= 직관적 이해

{intuition}

= 개념 시각화

#block(
  stroke: 0.5pt + gray,
  radius: 4pt,
  inset: 10pt,
  width: 100%,
)[
  #text(8pt, style: "italic")[시각화 전략: {viz_strategy}]
  #linebreak()
  ```
  {viz_code}
  ```
]

= 연관 개념 지도

#grid(
  columns: (1fr, 1fr),
  gutter: 1em,
  [
    *선행 개념*
{prereqs}
  ],
  [
    *응용 분야*
{apps}
  ],
  [
    *일반화*
{gens}
  ],
  [
    *특수 케이스*
{cases}
  ],
)
"""
